// Generated by Wrangler on Thu Sep 12 2024 00:49:02 GMT+0100 (British Summer Time)
// by running `wrangler types`

interface Env {
	STATE_KV: KVNamespace;
	DIRECTADMIN_BASE_URL: "https://mailadmin.0456456.xyz:2222";
	TURSO_URL: "libsql://directadmin-ingest-testdb-456dev.turso.io";
	DIRECTADMIN_MAILLOG_MAX_AGE: 2592000000;
	DIRECTADMIN_MAILLOG_FETCH_MAX: 604800000;
	TURSO_AUTH_TOKEN: string;
	DIRECTADMIN_LOGIN_TOKEN: string;
	DIRECTADMIN_LOGIN_USERNAME: string;
	DISCORD_WEBHOOK_URL: string;
	FETCH_MAGIC_PATH: string;
	DEPLOYMENT_USERAGENT_CONTACT: string;
}
